spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/mscourserealm

server:
  port: 8765

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
        defaultZone: http://eureka-admin:NatUALRogrES@localhost:8761/eureka/